/*
 * Created on 13 Jan 2009
 */
package com.griffinbrown.shail;

import java.util.HashMap;

/**
 * Interface to build XML documents using the Shail event model.  
 * Documents built using this interface are expected to manage a byte array
 * of events generated by a SAX parser.
 * @author andrews
 *
 * $Id$
 */
public interface Builder
{
    /**
     * Accesses the events associated with the document built. 
     * @return the events generated in building a given document
     */
    public byte[] getEvents();
    
    /**
     * Accesses a map of IDs populated during the document build.
     * @return
     */
    public HashMap getIdMap();
    
    /**
     * Accesses the StringHandler used during the document build.
     * @return
     */
    public StringHandler getStringHandler();
}
